### PR TITLE
First branch

### PR DESCRIPTION
**Pull request by ididmitrov**
In this PR we have new HTML and new CSS file with some content

### CODE REVIEW

**Comment by ididmitrov** [comment]
we need better styles for this css file

**Comment by CtrlJBG** [comment]
аз през цялото време се опитвах през gitbash да направя схемата

**Comment by godguard** [comment]
Bugs are endless :)

**Comment by ididmitrov** [comment]
> Bugs are endless :)

:(

**Comment by Zlatimir** [comment]
This is my comment

**Comment by CtrlJBG** [comment]
почти като в MIRC-ата е :D

**Comment by Vicente-pix** [comment]
so far so good

**Comment by jonkataa** [comment]
We need more of those exercises. 👍

**Comment by Vicente-pix** [comment]
[Branch Statement Path Coverage.txt](https://github.com/user-attachments/files/15890595/Branch.Statement.Path.Coverage.txt)

**Pull request merged**
